
# THIS FILE IS GENERATED BY SCRIPT
# DO NOT MODIFY

from .interop import *
from .entity import Entity

def entity_update_components(e: Entity):
    ptr = uw_interop.uwEntityPointer(e.id)

    c_Proto = uw_interop.uwFetchProtoComponent(ptr)
    if c_Proto[0]:
        e.Proto = c_Proto[1]
    else:
        e.Proto = None

    c_Owner = uw_interop.uwFetchOwnerComponent(ptr)
    if c_Owner[0]:
        e.Owner = c_Owner[1]
    else:
        e.Owner = None

    c_Controller = uw_interop.uwFetchControllerComponent(ptr)
    if c_Controller[0]:
        e.Controller = c_Controller[1]
    else:
        e.Controller = None

    c_Position = uw_interop.uwFetchPositionComponent(ptr)
    if c_Position[0]:
        e.Position = c_Position[1]
    else:
        e.Position = None

    c_Unit = uw_interop.uwFetchUnitComponent(ptr)
    if c_Unit[0]:
        e.Unit = c_Unit[1]
    else:
        e.Unit = None

    c_Life = uw_interop.uwFetchLifeComponent(ptr)
    if c_Life[0]:
        e.Life = c_Life[1]
    else:
        e.Life = None

    c_Mana = uw_interop.uwFetchManaComponent(ptr)
    if c_Mana[0]:
        e.Mana = c_Mana[1]
    else:
        e.Mana = None

    c_Move = uw_interop.uwFetchMoveComponent(ptr)
    if c_Move[0]:
        e.Move = c_Move[1]
    else:
        e.Move = None

    c_Aim = uw_interop.uwFetchAimComponent(ptr)
    if c_Aim[0]:
        e.Aim = c_Aim[1]
    else:
        e.Aim = None

    c_Recipe = uw_interop.uwFetchRecipeComponent(ptr)
    if c_Recipe[0]:
        e.Recipe = c_Recipe[1]
    else:
        e.Recipe = None

    c_RecipeStatistics = uw_interop.uwFetchRecipeStatisticsComponent(ptr)
    if c_RecipeStatistics[0]:
        e.RecipeStatistics = c_RecipeStatistics[1]
    else:
        e.RecipeStatistics = None

    c_LogisticsTimestamp = uw_interop.uwFetchLogisticsTimestampComponent(ptr)
    if c_LogisticsTimestamp[0]:
        e.LogisticsTimestamp = c_LogisticsTimestamp[1]
    else:
        e.LogisticsTimestamp = None

    c_Priority = uw_interop.uwFetchPriorityComponent(ptr)
    if c_Priority[0]:
        e.Priority = c_Priority[1]
    else:
        e.Priority = None

    c_Amount = uw_interop.uwFetchAmountComponent(ptr)
    if c_Amount[0]:
        e.Amount = c_Amount[1]
    else:
        e.Amount = None

    c_Attachment = uw_interop.uwFetchAttachmentComponent(ptr)
    if c_Attachment[0]:
        e.Attachment = c_Attachment[1]
    else:
        e.Attachment = None

    c_Ping = uw_interop.uwFetchPingComponent(ptr)
    if c_Ping[0]:
        e.Ping = c_Ping[1]
    else:
        e.Ping = None

    c_Player = uw_interop.uwFetchPlayerComponent(ptr)
    if c_Player[0]:
        e.Player = c_Player[1]
    else:
        e.Player = None

    c_PlayerAiConfig = uw_interop.uwFetchPlayerAiConfigComponent(ptr)
    if c_PlayerAiConfig[0]:
        e.PlayerAiConfig = c_PlayerAiConfig[1]
    else:
        e.PlayerAiConfig = None

    c_Force = uw_interop.uwFetchForceComponent(ptr)
    if c_Force[0]:
        e.Force = c_Force[1]
    else:
        e.Force = None

    c_ForceDetails = uw_interop.uwFetchForceDetailsComponent(ptr)
    if c_ForceDetails[0]:
        e.ForceDetails = c_ForceDetails[1]
    else:
        e.ForceDetails = None

    c_ForeignPolicy = uw_interop.uwFetchForeignPolicyComponent(ptr)
    if c_ForeignPolicy[0]:
        e.ForeignPolicy = c_ForeignPolicy[1]
    else:
        e.ForeignPolicy = None

    c_DiplomacyProposal = uw_interop.uwFetchDiplomacyProposalComponent(ptr)
    if c_DiplomacyProposal[0]:
        e.DiplomacyProposal = c_DiplomacyProposal[1]
    else:
        e.DiplomacyProposal = None
