
// THIS FILE IS GENERATED BY SCRIPT
// DO NOT MODIFY

using System;
using System.Runtime.InteropServices;

namespace Unnatural
{
    public static class Interop
    {
#if UW_USE_OPTIMIZED_LIBRARY
        // non-hard library may crash the program if used incorrectly
        public const string LibName = "unnatural-uwapi";
#else
        // hardened library contains additional checks to verify proper use of the api
        public const string LibName = "unnatural-uwapi-hard";
#endif

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern ulong uwGetLobbyId();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern ulong uwGetUserId();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern ushort uwGetServerPort();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminSetMapSelection([MarshalAs(UnmanagedType.LPStr)] string path);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminSetGameSpeed(float speed);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminSetWeatherSpeed(float speed, float offset);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminStartGame();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminTerminateGame();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminPauseGame([MarshalAs(UnmanagedType.I1)] bool pause);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminSkipCutscene();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminAddAi(uint intendedRace, float difficulty);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminKickPlayer(uint playerId);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminPlayerSetAdmin(uint playerId, [MarshalAs(UnmanagedType.I1)] bool admin);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminPlayerSetName(uint playerId, [MarshalAs(UnmanagedType.LPStr)] string name);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminPlayerAiConfig(uint playerId, ref UwPlayerAiConfigComponent config);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminPlayerJoinForce(uint playerId, uint forceId);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminForceJoinTeam(uint forceId, uint team);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminForceSetColor(uint forceId, float r, float g, float b);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminForceSetRace(uint forceId, uint raceProto);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminSendSuggestedCameraFocus(uint position);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminSetAutomaticSuggestedCameraFocus([MarshalAs(UnmanagedType.I1)] bool enabled);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminSendChat([MarshalAs(UnmanagedType.LPStr)] string msg, UwChatTargetFlags flags,
                                                  uint targetId);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAdminSendPing(uint position, UwPingEnum ping, uint targetForce);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwInitialize(uint version);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwDeinitialize();

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void UwExceptionCallbackType([MarshalAs(UnmanagedType.LPStr)] string message);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetExceptionCallback(UwExceptionCallbackType callback);

        public enum UwSeverityEnum
        {
            Note = 0,
            Hint = 1,
            Warning = 2,
            Info = 3,
            Error = 4,
            Critical = 5,
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct UwLogCallback
        {
            public IntPtr message;
            public IntPtr component;
            public UwSeverityEnum severity;
        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void UwLogCallbackType(ref UwLogCallback data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetLogCallback(UwLogCallbackType callback);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwInitializeConsoleLogger();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwLog(UwSeverityEnum severity, [MarshalAs(UnmanagedType.LPStr)] string message);

        public enum UwConnectionStateEnum
        {
            None = 0,
            Connecting = 1,
            Connected = 2,
            Error = 3,
        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void UwConnectionStateCallbackType(UwConnectionStateEnum state);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetConnectionStateCallback(UwConnectionStateCallbackType callback);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern UwConnectionStateEnum uwConnectionState();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetConnectStartGui([MarshalAs(UnmanagedType.I1)] bool enabled,
                                                       [MarshalAs(UnmanagedType.LPStr)] string extraCmdParams);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwConnectFindLan(ulong timeoutMicroseconds);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwConnectDirect([MarshalAs(UnmanagedType.LPStr)] string address, ushort port);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwConnectLobbyId(ulong lobbyId);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwConnectEnvironment();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwConnectNewServer(uint visibility, [MarshalAs(UnmanagedType.LPStr)] string name,
                                                     [MarshalAs(UnmanagedType.LPStr)] string extraCmdParams);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwTryReconnect();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwDisconnect();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetPlayerName([MarshalAs(UnmanagedType.LPStr)] string name);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwPlayerJoinForce(uint force);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetForceColor(float r, float g, float b);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetForceRace(uint raceProto);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwForceJoinTeam(uint team);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSkipCutscene();

        [StructLayout(LayoutKind.Sequential)]
        public struct UwMyPlayer
        {
            public uint playerEntityId;
            public uint forceEntityId;
            [MarshalAs(UnmanagedType.I1)]
            public bool primaryController;
            [MarshalAs(UnmanagedType.I1)]
            public bool admin;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwMyPlayer(ref UwMyPlayer data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwAssistConfig
        {
            [MarshalAs(UnmanagedType.I1)]
            public bool logistics;
            [MarshalAs(UnmanagedType.I1)]
            public bool aiming;
            [MarshalAs(UnmanagedType.I1)]
            public bool fighting;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetAssistConfig(ref UwAssistConfig config);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwPerformanceStatistics
        {
            public float gameSpeed;
            public float mainThreadUtilization;
            public float ping;
            public uint networkUp;
            public uint networkDown;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwPerformanceStatistics(ref UwPerformanceStatistics data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwPerformanceProfiling([MarshalAs(UnmanagedType.I1)] bool enable);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern ulong uwProfilingEventBegin();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwProfilingEventEnd([MarshalAs(UnmanagedType.LPStr)] string name,
                                                      ulong eventStartTime);

        public enum UwOrderTypeEnum
        {
            None = 0,
            Stop = 1,
            Guard = 2,
            Run = 3,
            Fight = 4,
            Load = 5,
            Unload = 6,
            SelfDestruct = 7,
        }

        [Flags]
        public enum UwOrderPriorityFlags
        {
            None = 0,
            Assistant = 1 << 0,
            User = 1 << 1,
            Enqueue = 1 << 2,
            Repeat = 1 << 3,
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct UwOrder
        {
            public uint entity;
            public uint position;
            public UwOrderTypeEnum order;
            public UwOrderPriorityFlags priority;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwOrder(uint unit, ref UwOrder data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwOrders
        {
            public IntPtr orders;
            public uint count;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwOrders(uint unit, ref UwOrders data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwCommandPlaceConstruction(uint constructionProto, uint position, float yaw,
                                                             uint recipeProto, UwPriorityEnum priority);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwCommandSetRecipe(uint unitOrConstructionId, uint recipeProto);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwCommandSetPriority(uint unitOrConstructionId, UwPriorityEnum priority);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwCommandLoad(uint unitId, uint resourceProto);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwCommandUnload(uint unitId);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwCommandMove(uint unitId, uint position, float yaw);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwCommandAim(uint unitId, uint targetId);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwCommandRenounceControl(uint entityId);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwCommandSelfDestruct(uint entityId);

        public const uint UW_VERSION = 43;
        public const uint UW_GameTicksPerSecond = 20;
        [StructLayout(LayoutKind.Sequential)]
        public struct UwIds
        {
            public IntPtr ids;
            public uint count;
        }

        public enum UwPriorityEnum
        {
            Disabled = 0,
            Normal = 1,
            High = 2,
        }

        public enum UwPingEnum
        {
            None = 0,
            Attention = 1,
            Attack = 2,
            Defend = 3,
            Rally = 4,
            Build = 5,
            Evacuate = 6,
        }

        public enum UwPathStateEnum
        {
            None = 0,
            Searching = 1,
            Impossible = 2,
            NotFound = 3,
            Recompute = 4,
            Found = 5,
            Finished = 6,
        }

        public enum UwForeignPolicyEnum
        {
            None = 0,
            Self = 1,
            Ally = 2,
            Neutral = 3,
            Enemy = 4,
        }

        [Flags]
        public enum UwChatTargetFlags
        {
            None = 0,
            Server = 1 << 0,
            Direct = 1 << 1,
            Self = 1 << 2,
            Allies = 1 << 3,
            Neutral = 1 << 4,
            Enemy = 1 << 5,
            Observer = 1 << 6,
            Admin = 1 << 7,
            Players = Self | Allies | Neutral | Enemy,
            Everyone = Players | Observer | Admin,
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr uwEntityPointer(uint id);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint uwEntityId(IntPtr entity);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwModifiedEntities(ref UwIds data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAllEntities(ref UwIds data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwEntityExists(uint id);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwProtoComponent
        {
            public uint proto;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchProtoComponent(IntPtr entity, ref UwProtoComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwOwnerComponent
        {
            public uint force;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchOwnerComponent(IntPtr entity, ref UwOwnerComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwControllerComponent
        {
            public uint player;
            public uint timestamp;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchControllerComponent(IntPtr entity, ref UwControllerComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwPositionComponent
        {
            public uint position;
            public float yaw;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchPositionComponent(IntPtr entity, ref UwPositionComponent data);

        [Flags]
        public enum UwUnitStateFlags
        {
            None = 0,
            Shooting = 1 << 0,
            Processing = 1 << 1,
            Rebuilding = 1 << 2,
            Stalling = 1 << 3,
            Damaged = 1 << 4,
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct UwUnitComponent
        {
            public UwUnitStateFlags state;
            public uint killCount;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchUnitComponent(IntPtr entity, ref UwUnitComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwLifeComponent
        {
            public int life;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchLifeComponent(IntPtr entity, ref UwLifeComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwManaComponent
        {
            public int mana;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchManaComponent(IntPtr entity, ref UwManaComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwMoveComponent
        {
            public uint timestamp;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchMoveComponent(IntPtr entity, ref UwMoveComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwAimComponent
        {
            public uint target;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchAimComponent(IntPtr entity, ref UwAimComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwRecipeComponent
        {
            public uint recipe;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchRecipeComponent(IntPtr entity, ref UwRecipeComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwRecipeStatisticsComponent
        {
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public uint[] timestamps;
            public uint completed;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchRecipeStatisticsComponent(IntPtr entity, ref UwRecipeStatisticsComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwLogisticsTimestampComponent
        {
            public uint timestamp;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchLogisticsTimestampComponent(IntPtr entity,
                                                                     ref UwLogisticsTimestampComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwPriorityComponent
        {
            public UwPriorityEnum priority;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchPriorityComponent(IntPtr entity, ref UwPriorityComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwAmountComponent
        {
            public uint amount;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchAmountComponent(IntPtr entity, ref UwAmountComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwAttachmentComponent
        {
            public uint target;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchAttachmentComponent(IntPtr entity, ref UwAttachmentComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwPingComponent
        {
            public UwPingEnum ping;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchPingComponent(IntPtr entity, ref UwPingComponent data);

        [Flags]
        public enum UwPlayerStateFlags
        {
            None = 0,
            Disconnected = 1 << 0,
            Admin = 1 << 1,
            Loaded = 1 << 2,
            Pause = 1 << 3,
            SkipCutscene = 1 << 4,
        }

        public enum UwPlayerConnectionClassEnum
        {
            None = 0,
            Computer = 1,
            VirtualReality = 2,
            Robot = 3,
            UwApi = 4,
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct UwPlayerComponent
        {
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 28)]
            public char[] name;
            public uint nameLength;
            public ulong steamUserId;
            public uint force;
            public float progress;
            public uint ping;
            public UwPlayerStateFlags state;
            public UwPlayerConnectionClassEnum playerConnectionClass;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchPlayerComponent(IntPtr entity, ref UwPlayerComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwPlayerAiConfigComponent
        {
            public float difficulty;
            public float aggressive;
            public float stretching;
            public float expansive;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchPlayerAiConfigComponent(IntPtr entity, ref UwPlayerAiConfigComponent data);

        [Flags]
        public enum UwForceStateFlags
        {
            None = 0,
            Disconnected = 1 << 0,
            Winner = 1 << 1,
            Defeated = 1 << 2,
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct UwForceComponent
        {
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public float[] color;
            public ulong score;
            public uint killCount;
            public uint lossCount;
            public uint finishTimestamp;
            public uint intendedTeam;
            public uint intendedRace;
            public UwForceStateFlags state;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchForceComponent(IntPtr entity, ref UwForceComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwForceDetailsComponent
        {
            public ulong killValue;
            public ulong lossValue;
            public uint startingPosition;
            public uint race;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchForceDetailsComponent(IntPtr entity, ref UwForceDetailsComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwForeignPolicyComponent
        {
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
            public uint[] forces;
            public UwForeignPolicyEnum policy;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchForeignPolicyComponent(IntPtr entity, ref UwForeignPolicyComponent data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwDiplomacyProposalComponent
        {
            public uint offeror;
            public uint offeree;
            public UwForeignPolicyEnum proposal;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwFetchDiplomacyProposalComponent(IntPtr entity,
                                                                    ref UwDiplomacyProposalComponent data);

        public enum UwGameStateEnum
        {
            None = 0,
            Session = 1,
            Preparation = 2,
            Starting = 3,
            Game = 4,
            Pause = 5,
            CutscenePaused = 6,
            CutsceneRunning = 7,
            Finish = 8,
        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void UwGameStateCallbackType(UwGameStateEnum state);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetGameStateCallback(UwGameStateCallbackType callback);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern UwGameStateEnum uwGameState();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint uwGameTick();

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void UwUpdateCallbackType([MarshalAs(UnmanagedType.I1)] bool stepping);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetUpdateCallback(UwUpdateCallbackType callback);

        public enum UwShootingEventEnum
        {
            None = 0,
            Shooting = 1,
            Death = 2,
            Explosion = 3,
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct UwShootingsArray
        {
            public IntPtr data;
            public uint count;
        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void UwShootingsCallbackType(ref UwShootingsArray data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetShootingsCallback(UwShootingsCallbackType callback);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void UwForceEliminatedCallbackType(uint id);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetForceEliminatedCallback(UwForceEliminatedCallbackType callback);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void UwChatCallbackType([MarshalAs(UnmanagedType.LPStr)] string msg, uint sender,
                                                UwChatTargetFlags flags);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetChatCallback(UwChatCallbackType callback);

        public enum UwTaskTypeEnum
        {
            None = 0,
            UnitPathfinding = 1,
            ClustersDistances = 2,
        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void UwTaskCompletedCallbackType(ulong taskUserData, UwTaskTypeEnum type);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetTaskCompletedCallback(UwTaskCompletedCallbackType callback);

        public enum UwMapStateEnum
        {
            None = 0,
            Downloading = 1,
            Loading = 2,
            Loaded = 3,
            Unloading = 4,
            Error = 5,
        }

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        public delegate void UwMapStateCallbackType(UwMapStateEnum state);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwSetMapStateCallback(UwMapStateCallbackType callback);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern UwMapStateEnum uwMapState();

        [StructLayout(LayoutKind.Sequential)]
        public struct UwMapInfo
        {
            public IntPtr name;
            public IntPtr guid;
            public IntPtr path;
            public uint maxPlayers;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwMapInfo(ref UwMapInfo data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwMapStartingPosition
        {
            public uint position;
            public uint minForces;
            public uint maxForces;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct UwMapStartingPositionsArray
        {
            public IntPtr data;
            public uint count;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwMapStartingPositions(ref UwMapStartingPositionsArray data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint uwTilesCount();

        [StructLayout(LayoutKind.Sequential)]
        public struct UwTile
        {
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public float[] position;
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
            public float[] up;
            public IntPtr neighborsIndices;
            public uint neighborsCount;
            public uint clusterIndex;
            public byte terrain;
            [MarshalAs(UnmanagedType.I1)]
            public bool border;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwTile(uint index, ref UwTile data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint uwClustersCount();

        [StructLayout(LayoutKind.Sequential)]
        public struct UwCluster
        {
            public IntPtr neighborsIndices;
            public uint neighborsCount;
            public uint centerTileIndex;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwCluster(uint index, ref UwCluster data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAreaRange(float x, float y, float z, float radius, ref UwIds data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAreaConnected(uint position, float radius, ref UwIds data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAreaNeighborhood(uint position, float radius, ref UwIds data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAreaExtended(uint position, float radius, ref UwIds data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwTestVisible(float x1, float y1, float z1, float x2, float y2, float z2);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwTestShooting(uint shooterPosition, uint shooterProto, float shootingRangeUpgrade,
                                                 uint targetPosition, uint targetProto);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern float uwDistanceLine(float x1, float y1, float z1, float x2, float y2, float z2);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern float uwDistanceEstimate(uint positionA, uint positionB);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern float uwYaw(uint startPosition, uint goalPosition);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwClustersDistancesQuery
        {
            public ulong taskUserData;
            public uint startingCluster;
            public uint unitPrototype;
            [MarshalAs(UnmanagedType.I1)]
            public bool allowImpassableTerrain;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct UwClustersDistancesResult
        {
            public UwIds distances;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwStartClustersDistances(ref UwClustersDistancesQuery query);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwRetrieveClustersDistances(ref UwClustersDistancesResult data);

        public enum UwPrototypeTypeEnum
        {
            None = 0,
            Resource = 1,
            Recipe = 2,
            Construction = 3,
            Unit = 4,
            Upgrade = 5,
            Race = 6,
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwAllPrototypes(ref UwIds data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern UwPrototypeTypeEnum uwPrototypeType(uint prototypeId);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr uwPrototypeJson(uint prototypeId);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr uwDefinitionsJson();

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint uwHashString([MarshalAs(UnmanagedType.LPStr)] string str);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwMyForceStatistics
        {
            public uint logisticsUnitsIdle;
            public uint logisticsUnitsTotal;
            public uint militaryUnitsIdle;
            public uint militaryUnitsTotal;
            public uint closestDangerPosition;
            public float closestDangerDistance;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwMyForceStatistics(ref UwMyForceStatistics data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern UwPathStateEnum uwUnitPathState(uint unitId);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwUnitUpgrades
        {
            public float damage;
            public float shootingRange;
            public float splashRadius;
            public float defense;
            public float regenSpeed;
            public float movementSpeed;
            public float processingSpeed;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwUnitUpgrades(uint unit, ref UwUnitUpgrades data);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwTestShootingEntities(uint shooterId, uint targetId);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        [return:MarshalAs(UnmanagedType.I1)]
        public static extern bool uwTestConstructionPlacement(uint constructionProto, uint position, uint recipeProto);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern uint uwFindConstructionPlacement(uint constructionProto, uint position, uint recipeProto);

        [Flags]
        public enum UwOverviewFlags
        {
            None = 0,
            Resource = 1 << 0,
            Construction = 1 << 1,
            MobileUnit = 1 << 2,
            StaticUnit = 1 << 3,
            Unit = MobileUnit | StaticUnit,
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern UwOverviewFlags uwOverviewFlags(uint position);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwOverviewIds(uint position, ref UwIds data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwOverviewExtract
        {
            public IntPtr flags;
            public uint count;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwOverviewExtract(ref UwOverviewExtract data);

        [StructLayout(LayoutKind.Sequential)]
        public struct UwUnitPathfindingQuery
        {
            public ulong taskUserData;
            public uint startingPosition;
            public uint goalPosition;
            public uint unitPrototype;
            public uint maxIterations;
            [MarshalAs(UnmanagedType.I1)]
            public bool allowNearbyPosition;
        }

        [StructLayout(LayoutKind.Sequential)]
        public struct UwUnitPathfindingResult
        {
            public UwIds path;
            public UwPathStateEnum state;
        }

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwStartUnitPathfinding(ref UwUnitPathfindingQuery query);

        [DllImport(LibName, CallingConvention = CallingConvention.Cdecl)]
        public static extern void uwRetrieveUnitPathfinding(ref UwUnitPathfindingResult data);
    }

    public partial class Entity
    {
        public Interop.UwProtoComponent? Proto;
        public Interop.UwOwnerComponent? Owner;
        public Interop.UwControllerComponent? Controller;
        public Interop.UwPositionComponent? Position;
        public Interop.UwUnitComponent? Unit;
        public Interop.UwLifeComponent? Life;
        public Interop.UwManaComponent? Mana;
        public Interop.UwMoveComponent? Move;
        public Interop.UwAimComponent? Aim;
        public Interop.UwRecipeComponent? Recipe;
        public Interop.UwRecipeStatisticsComponent? RecipeStatistics;
        public Interop.UwLogisticsTimestampComponent? LogisticsTimestamp;
        public Interop.UwPriorityComponent? Priority;
        public Interop.UwAmountComponent? Amount;
        public Interop.UwAttachmentComponent? Attachment;
        public Interop.UwPingComponent? Ping;
        public Interop.UwPlayerComponent? Player;
        public Interop.UwPlayerAiConfigComponent? PlayerAiConfig;
        public Interop.UwForceComponent? Force;
        public Interop.UwForceDetailsComponent? ForceDetails;
        public Interop.UwForeignPolicyComponent? ForeignPolicy;
        public Interop.UwDiplomacyProposalComponent? DiplomacyProposal;

        public void FetchComponents()
        {
            IntPtr e = Interop.uwEntityPointer(Id);
            {
                Interop.UwProtoComponent tmp = new Interop.UwProtoComponent();
                if (Interop.uwFetchProtoComponent(e, ref tmp))
                    Proto = tmp;
                else
                    Proto = null;
            }
            {
                Interop.UwOwnerComponent tmp = new Interop.UwOwnerComponent();
                if (Interop.uwFetchOwnerComponent(e, ref tmp))
                    Owner = tmp;
                else
                    Owner = null;
            }
            {
                Interop.UwControllerComponent tmp = new Interop.UwControllerComponent();
                if (Interop.uwFetchControllerComponent(e, ref tmp))
                    Controller = tmp;
                else
                    Controller = null;
            }
            {
                Interop.UwPositionComponent tmp = new Interop.UwPositionComponent();
                if (Interop.uwFetchPositionComponent(e, ref tmp))
                    Position = tmp;
                else
                    Position = null;
            }
            {
                Interop.UwUnitComponent tmp = new Interop.UwUnitComponent();
                if (Interop.uwFetchUnitComponent(e, ref tmp))
                    Unit = tmp;
                else
                    Unit = null;
            }
            {
                Interop.UwLifeComponent tmp = new Interop.UwLifeComponent();
                if (Interop.uwFetchLifeComponent(e, ref tmp))
                    Life = tmp;
                else
                    Life = null;
            }
            {
                Interop.UwManaComponent tmp = new Interop.UwManaComponent();
                if (Interop.uwFetchManaComponent(e, ref tmp))
                    Mana = tmp;
                else
                    Mana = null;
            }
            {
                Interop.UwMoveComponent tmp = new Interop.UwMoveComponent();
                if (Interop.uwFetchMoveComponent(e, ref tmp))
                    Move = tmp;
                else
                    Move = null;
            }
            {
                Interop.UwAimComponent tmp = new Interop.UwAimComponent();
                if (Interop.uwFetchAimComponent(e, ref tmp))
                    Aim = tmp;
                else
                    Aim = null;
            }
            {
                Interop.UwRecipeComponent tmp = new Interop.UwRecipeComponent();
                if (Interop.uwFetchRecipeComponent(e, ref tmp))
                    Recipe = tmp;
                else
                    Recipe = null;
            }
            {
                Interop.UwRecipeStatisticsComponent tmp = new Interop.UwRecipeStatisticsComponent();
                if (Interop.uwFetchRecipeStatisticsComponent(e, ref tmp))
                    RecipeStatistics = tmp;
                else
                    RecipeStatistics = null;
            }
            {
                Interop.UwLogisticsTimestampComponent tmp = new Interop.UwLogisticsTimestampComponent();
                if (Interop.uwFetchLogisticsTimestampComponent(e, ref tmp))
                    LogisticsTimestamp = tmp;
                else
                    LogisticsTimestamp = null;
            }
            {
                Interop.UwPriorityComponent tmp = new Interop.UwPriorityComponent();
                if (Interop.uwFetchPriorityComponent(e, ref tmp))
                    Priority = tmp;
                else
                    Priority = null;
            }
            {
                Interop.UwAmountComponent tmp = new Interop.UwAmountComponent();
                if (Interop.uwFetchAmountComponent(e, ref tmp))
                    Amount = tmp;
                else
                    Amount = null;
            }
            {
                Interop.UwAttachmentComponent tmp = new Interop.UwAttachmentComponent();
                if (Interop.uwFetchAttachmentComponent(e, ref tmp))
                    Attachment = tmp;
                else
                    Attachment = null;
            }
            {
                Interop.UwPingComponent tmp = new Interop.UwPingComponent();
                if (Interop.uwFetchPingComponent(e, ref tmp))
                    Ping = tmp;
                else
                    Ping = null;
            }
            {
                Interop.UwPlayerComponent tmp = new Interop.UwPlayerComponent();
                if (Interop.uwFetchPlayerComponent(e, ref tmp))
                    Player = tmp;
                else
                    Player = null;
            }
            {
                Interop.UwPlayerAiConfigComponent tmp = new Interop.UwPlayerAiConfigComponent();
                if (Interop.uwFetchPlayerAiConfigComponent(e, ref tmp))
                    PlayerAiConfig = tmp;
                else
                    PlayerAiConfig = null;
            }
            {
                Interop.UwForceComponent tmp = new Interop.UwForceComponent();
                if (Interop.uwFetchForceComponent(e, ref tmp))
                    Force = tmp;
                else
                    Force = null;
            }
            {
                Interop.UwForceDetailsComponent tmp = new Interop.UwForceDetailsComponent();
                if (Interop.uwFetchForceDetailsComponent(e, ref tmp))
                    ForceDetails = tmp;
                else
                    ForceDetails = null;
            }
            {
                Interop.UwForeignPolicyComponent tmp = new Interop.UwForeignPolicyComponent();
                if (Interop.uwFetchForeignPolicyComponent(e, ref tmp))
                    ForeignPolicy = tmp;
                else
                    ForeignPolicy = null;
            }
            {
                Interop.UwDiplomacyProposalComponent tmp = new Interop.UwDiplomacyProposalComponent();
                if (Interop.uwFetchDiplomacyProposalComponent(e, ref tmp))
                    DiplomacyProposal = tmp;
                else
                    DiplomacyProposal = null;
            }
        }
    }
}
